version: "3.9"

services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  web:
    image: mud/mudserver
    build:
      context: .
      network: "host"
    command: daphne mudserver.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - ./mudserver:/code
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis